---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workload-apps-mon1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io  
spec:
  project: applications-project-mon1
  source:
    repoURL: git@github.com:Mohit-Verma-1688/crossplane-eks.git
    targetRevision: HEAD
    path: crossplane-apps
    helm:
      values: |
        spec:
          destination:
            server: https://31574EDDB2731071DBC51AB925ED3A12.gr7.us-east-1.eks.amazonaws.com 
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true 
