apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgCK6EgktovPzeZo+IiWgADWRM0ym7YfsDaZrMgKP+S8wWV8TfkwY+MsfOVOLQVzcU1B9462edYZj9LNz9IfevL24t2acHka8bjUK0Y1ty25/TAoOb5sYCy7sPQuTIxdBJGSfHk+S1XCL9dfe9h9F4sXwZQJoNICcS9JCf4ERdOhnakat0pWdDaOqid5lPLBwZWG+WOZj8V4dj3lEi2AeTw+M2j/1lodnzcgiS5MLAu98uXI2BbxGF/YHjnJG42FZLksOQXcnMbG4jJ7+XV2GJg6jrVU79fwNsj2SWpsrSTMrJaH2Fe4omnXZ6JfklEI5JxL7AF/JNwMU4J3fbKIau2vz3ZPKVV/7FbLOfESkazHYNgb3a673OgbVp/44K1i+8vIq8S4wkv+Ap9V9eQD+gmXVjPRuk7WwtZOjDvv/9UssxsZiUfgVFwcQHvbkR1471YQ3BGswdnf90EusbxqwHXR8nDDbXX+WJuVvYtvhiSJAyA6r8igDAmBdqb6HkuI6qLBfb2rMqeCyc7RHgs150nViAEAFLlCVUyWRhGqtHjwnUe2DpnWgeAyEIUdJbzK6HBwGllpb8k2uIAljrJeoxdpHw/BFhgsuyjyrAqZ6YcmXs7KupRKrzzmx/lnowuNBh+QyTuvK7iN1dbKMP+gQgIbLqTSUn4UqucAexo1kv/HG/8VVxiFBEAA7uC/qpWZwGt79wOIptK+8BnWgr6XHitBUUxyaWKzdoo3vjzSxM4OfucC2yuHNot3WD9wfkRwQkK0tz4mEgYXkTelh6LORVoXm4nUTQZPVLCqGA0NRac2qWP7ZR43oBykaU9t9vQy0nJHewEAvG/MbCKdCLekmlHnLVsCtg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: crossplane-system
    type: Opaque

