apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgDd04riCNQ4IkeYLhuLy+zbNkZJ+huFbg1QFPpwiS7meo54WU60zo2UCMh3x9QC0vu+TmrbhkEDLpoaHsp+Mb8ur6xcpNvEivH8nMa9J5tbMIqDb3ZUuDk1UuUFPHknrodTFvoD2pzUD0tcoanJc2izXYo+WA6xjvD7hWtRIZTSNWwNbtBnsnPabhVjYSpcpdceBYHBjzarIfTh0Z/D6r1t7chJGywmUTy/qpd3kq7Wn2Pi/Zn1m2B9qDFTrAfjxlIGoMBYCr9KCJ+1q2NrJ3eXIzmZ/QQeXuFJricpwvuFDjuUtiL3Uwr/gesp8/Xb+iD3JFXN9FuQ7XtrDB9sOmiu/mjGdC+yGcf56AkEDnE2f32peCP7mQ3/wYPz9XdBKXXtz1PRC0J5yeCO9uf4duwQSsHkpAyHn1g87P8i4yQrWByXUXEyZ3bnIMsaAKqFWTt6wKLLAuLYsrWAyevlI/q7SPgn+5Do95JQRcseSFWXDe3VCYVNTTuOfICmsvsqifvtS3IjCKtpsmRyG9Ecp0NlDs7PFdq7CW+/fzVyTpH/D0Ecw17cM5xbAfA/wKaycMr1JmaYQM8SGMocUWN1j4owP5xrGKX6awWiHtclXVYS1R34eJDE3xs81amKrUDmwYN3U+qjRE9598y7soWFnQkH6fQ3hVPtp0/rBZcwOG6H0fIQir07iJvDKJEPH2NPTPPHzHHOcVFGZnsEua1fpQ8Rkv7zSmuV3e1K6d6KHl9qys7HVMDz4gZ/PYWIgw5eSPCh028PscYocbgTitd066PFhfZxD528oVMl2aHVhnFt4Rq5fLLAcAwLsm49HVhCWuyjoGXFjLNSk7CbxeIaRN6a7hVzeQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: crossplane
    type: Opaque

