apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: crossplane
spec:
  encryptedData:
    creds: AgByLMZzqhbOAlZkh0t+29bF3W/Yi5KFGooz/PFHNPQSJfX60qm4AL2XtJWPAeV3TGNDXPTOOSev0o+nIIR5TbtiWmh7vsYtLi+DwhB/uDHAMElIEV0Kb5ZA7ZoAL5JYCjJ8HaI+q6mUc8yTrzLFm/759Qs3UMB9SmAOkyoNy3yaSPfnFaz5gtNOZ/+3MMFDkH6FeVmAn9+Q5gmasJGQh8bADK264ZDYwQpTjjazpK3W/3XLA7ggmqCwobqLrWNvYz9rG5wtQSYlJhikSULE4aJ1XNplhXcmXjfKHT7gX7Z9W+qNH3nuJLB1/JJk9+svG2d/LRyj33ymlYUq3S5Zuav0MY46C3hoFJDN+YuQzqVqREG17mox7tIM/4zqEx5DqPIY/FObZh8S6N5SPp2tD1BmTP68VqLwCz0Zs5ZkWbwHS62RW8pdgkJbLjSw3NnnKAp91WW6/NvSM4cuW00ZjsxSLepOXuSd7FLyNQEpR1pmAKw5wAV/7QxPQKGeS1W6y3aw8B2DxIsLkpSI0XwTKeO7nPKOTdRDNOgOtBmYHk/UP2Rdh6ewyc+zRx9hZdrSVFfY/lm9MvoxkSMqBDt8o+1MnxsSa1XM3QDLHiEhxBkAptpu4T0SpGdcfuUQGKxjX+4Eh3ecdzRj4h0DCzbrBYli8+gSDzTYva4VEj4ou3K1L3+WNFjwJFZkucnpUD499D5LMjpXW8b0r14LK710vCbYEuYKJ4kPnQ/nndsu8Vh44VIugdE8MkURR09kjyGcf2RQst3dV2YyzLDCVLXy3Ad44lGVS7xbOzU6o3EVH7jbxOH2ubcWXZiwWxeUtDDitmIdenYTd9Zws+TVjjNB9LprmAtX+g==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: crossplane
    type: Opaque

---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: after-aws-cred
  namespace: crossplane
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "5"
spec:
  template:
    spec:
      containers:
        - name: page-down
          image: alpine:latest
          command: ["sleep", "10"]
      restartPolicy: Never
