---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-dns01-prod
  namespace: demo-webapp
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mohit_verma160288@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-dns01-key-pair
    solvers:
    - dns01:
        route53:
          region: us-east-1
          hostedZoneID: Z100992510LUGZYBTY35U
