apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: app
    app.kubernetes.io/instance: php-frontend
  name: web
  namespace: demo-webapp
spec:
  ports:
  - name: port-1
    port: 80
    protocol: TCP
    targetPort: 80
  - name: port-2
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: app
  type: LoadBalancer
status:
  loadBalancer: {}
